// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autopilotrpc/autopilot.proto

/*
Package autopilotrpc is a generated protocol buffer package.

It is generated from these files:
	autopilotrpc/autopilot.proto

It has these top-level messages:
	StatusRequest
	StatusResponse
	ModifyStatusRequest
	ModifyStatusResponse
	SetScoresRequest
	SetScoresResponse
	ScoresRequest
	ScoreReport
	ScoresResponse
*/
package autopilotrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusResponse struct {
	// / Indicates whether the autopilot is active or not.
	Active bool `protobuf:"varint,1,opt,name=active" json:"active,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatusResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ModifyStatusRequest struct {
	// / Whether the autopilot agent should be enabled or not.
	Enable bool `protobuf:"varint,1,opt,name=enable" json:"enable,omitempty"`
}

func (m *ModifyStatusRequest) Reset()                    { *m = ModifyStatusRequest{} }
func (m *ModifyStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*ModifyStatusRequest) ProtoMessage()               {}
func (*ModifyStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ModifyStatusRequest) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

type ModifyStatusResponse struct {
}

func (m *ModifyStatusResponse) Reset()                    { *m = ModifyStatusResponse{} }
func (m *ModifyStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*ModifyStatusResponse) ProtoMessage()               {}
func (*ModifyStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SetScoresRequest struct {
	Scores map[string]int64 `protobuf:"bytes,1,rep,name=scores" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *SetScoresRequest) Reset()                    { *m = SetScoresRequest{} }
func (m *SetScoresRequest) String() string            { return proto.CompactTextString(m) }
func (*SetScoresRequest) ProtoMessage()               {}
func (*SetScoresRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetScoresRequest) GetScores() map[string]int64 {
	if m != nil {
		return m.Scores
	}
	return nil
}

type SetScoresResponse struct {
}

func (m *SetScoresResponse) Reset()                    { *m = SetScoresResponse{} }
func (m *SetScoresResponse) String() string            { return proto.CompactTextString(m) }
func (*SetScoresResponse) ProtoMessage()               {}
func (*SetScoresResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ScoresRequest struct {
	Pubkeys []string `protobuf:"bytes,1,rep,name=pubkeys" json:"pubkeys,omitempty"`
}

func (m *ScoresRequest) Reset()                    { *m = ScoresRequest{} }
func (m *ScoresRequest) String() string            { return proto.CompactTextString(m) }
func (*ScoresRequest) ProtoMessage()               {}
func (*ScoresRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ScoresRequest) GetPubkeys() []string {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

type ScoreReport struct {
	Heuristic string `protobuf:"bytes,1,opt,name=heuristic" json:"heuristic,omitempty"`
	// TODO: avoid float?
	Scores map[string]float64 `protobuf:"bytes,2,rep,name=scores" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
}

func (m *ScoreReport) Reset()                    { *m = ScoreReport{} }
func (m *ScoreReport) String() string            { return proto.CompactTextString(m) }
func (*ScoreReport) ProtoMessage()               {}
func (*ScoreReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ScoreReport) GetHeuristic() string {
	if m != nil {
		return m.Heuristic
	}
	return ""
}

func (m *ScoreReport) GetScores() map[string]float64 {
	if m != nil {
		return m.Scores
	}
	return nil
}

type ScoresResponse struct {
	Reports []*ScoreReport `protobuf:"bytes,1,rep,name=reports" json:"reports,omitempty"`
}

func (m *ScoresResponse) Reset()                    { *m = ScoresResponse{} }
func (m *ScoresResponse) String() string            { return proto.CompactTextString(m) }
func (*ScoresResponse) ProtoMessage()               {}
func (*ScoresResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ScoresResponse) GetReports() []*ScoreReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "autopilotrpc.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "autopilotrpc.StatusResponse")
	proto.RegisterType((*ModifyStatusRequest)(nil), "autopilotrpc.ModifyStatusRequest")
	proto.RegisterType((*ModifyStatusResponse)(nil), "autopilotrpc.ModifyStatusResponse")
	proto.RegisterType((*SetScoresRequest)(nil), "autopilotrpc.SetScoresRequest")
	proto.RegisterType((*SetScoresResponse)(nil), "autopilotrpc.SetScoresResponse")
	proto.RegisterType((*ScoresRequest)(nil), "autopilotrpc.ScoresRequest")
	proto.RegisterType((*ScoreReport)(nil), "autopilotrpc.ScoreReport")
	proto.RegisterType((*ScoresResponse)(nil), "autopilotrpc.ScoresResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Autopilot service

type AutopilotClient interface {
	// *
	// Status returns whether the daemon's autopilot agent is active.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// *
	// ModifyStatus is used to modify the status of the autopilot agent, like
	// enabling or disabling it.
	ModifyStatus(ctx context.Context, in *ModifyStatusRequest, opts ...grpc.CallOption) (*ModifyStatusResponse, error)
	SetScores(ctx context.Context, in *SetScoresRequest, opts ...grpc.CallOption) (*SetScoresResponse, error)
	Scores(ctx context.Context, in *ScoresRequest, opts ...grpc.CallOption) (*ScoresResponse, error)
}

type autopilotClient struct {
	cc *grpc.ClientConn
}

func NewAutopilotClient(cc *grpc.ClientConn) AutopilotClient {
	return &autopilotClient{cc}
}

func (c *autopilotClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/autopilotrpc.Autopilot/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autopilotClient) ModifyStatus(ctx context.Context, in *ModifyStatusRequest, opts ...grpc.CallOption) (*ModifyStatusResponse, error) {
	out := new(ModifyStatusResponse)
	err := grpc.Invoke(ctx, "/autopilotrpc.Autopilot/ModifyStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autopilotClient) SetScores(ctx context.Context, in *SetScoresRequest, opts ...grpc.CallOption) (*SetScoresResponse, error) {
	out := new(SetScoresResponse)
	err := grpc.Invoke(ctx, "/autopilotrpc.Autopilot/SetScores", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autopilotClient) Scores(ctx context.Context, in *ScoresRequest, opts ...grpc.CallOption) (*ScoresResponse, error) {
	out := new(ScoresResponse)
	err := grpc.Invoke(ctx, "/autopilotrpc.Autopilot/Scores", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Autopilot service

type AutopilotServer interface {
	// *
	// Status returns whether the daemon's autopilot agent is active.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// *
	// ModifyStatus is used to modify the status of the autopilot agent, like
	// enabling or disabling it.
	ModifyStatus(context.Context, *ModifyStatusRequest) (*ModifyStatusResponse, error)
	SetScores(context.Context, *SetScoresRequest) (*SetScoresResponse, error)
	Scores(context.Context, *ScoresRequest) (*ScoresResponse, error)
}

func RegisterAutopilotServer(s *grpc.Server, srv AutopilotServer) {
	s.RegisterService(&_Autopilot_serviceDesc, srv)
}

func _Autopilot_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutopilotServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autopilotrpc.Autopilot/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutopilotServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Autopilot_ModifyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutopilotServer).ModifyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autopilotrpc.Autopilot/ModifyStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutopilotServer).ModifyStatus(ctx, req.(*ModifyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Autopilot_SetScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutopilotServer).SetScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autopilotrpc.Autopilot/SetScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutopilotServer).SetScores(ctx, req.(*SetScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Autopilot_Scores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutopilotServer).Scores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autopilotrpc.Autopilot/Scores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutopilotServer).Scores(ctx, req.(*ScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Autopilot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "autopilotrpc.Autopilot",
	HandlerType: (*AutopilotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Autopilot_Status_Handler,
		},
		{
			MethodName: "ModifyStatus",
			Handler:    _Autopilot_ModifyStatus_Handler,
		},
		{
			MethodName: "SetScores",
			Handler:    _Autopilot_SetScores_Handler,
		},
		{
			MethodName: "Scores",
			Handler:    _Autopilot_Scores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autopilotrpc/autopilot.proto",
}

func init() { proto.RegisterFile("autopilotrpc/autopilot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdd, 0x4e, 0xc2, 0x30,
	0x14, 0x4e, 0x47, 0x1c, 0xee, 0xf0, 0x23, 0x16, 0x42, 0xe6, 0x20, 0x8a, 0x4d, 0x4c, 0xa6, 0x89,
	0x33, 0x81, 0x1b, 0x35, 0xf1, 0x42, 0x0d, 0x77, 0x7a, 0x53, 0xe2, 0x03, 0x8c, 0x59, 0xe3, 0x02,
	0xa1, 0x73, 0xeb, 0x48, 0xf6, 0x18, 0x3e, 0x84, 0x2f, 0xe1, 0xd3, 0x19, 0xb6, 0x6e, 0x74, 0x04,
	0xb8, 0xf2, 0x6e, 0xdf, 0x39, 0x5f, 0xbf, 0xf3, 0x7d, 0xed, 0x19, 0xf4, 0xdd, 0x58, 0xf0, 0xc0,
	0x9f, 0x73, 0x11, 0x06, 0xde, 0x4d, 0x01, 0x9c, 0x20, 0xe4, 0x82, 0xe3, 0xba, 0xda, 0x25, 0x47,
	0xd0, 0x98, 0x08, 0x57, 0xc4, 0x11, 0x65, 0x5f, 0x31, 0x8b, 0x04, 0xb1, 0xa1, 0x99, 0x17, 0xa2,
	0x80, 0x2f, 0x22, 0x86, 0xbb, 0xa0, 0xbb, 0x9e, 0xf0, 0x97, 0xcc, 0x44, 0x03, 0x64, 0x1f, 0x52,
	0x89, 0xc8, 0x35, 0xb4, 0x5f, 0xf9, 0xbb, 0xff, 0x91, 0x94, 0x04, 0x56, 0x74, 0xb6, 0x70, 0xa7,
	0xf3, 0x82, 0x9e, 0x21, 0xd2, 0x85, 0x4e, 0x99, 0x9e, 0xc9, 0x93, 0x6f, 0x04, 0xad, 0x09, 0x13,
	0x13, 0x8f, 0x87, 0xac, 0x10, 0x79, 0x02, 0x3d, 0x4a, 0x0b, 0x26, 0x1a, 0x54, 0xec, 0xda, 0xf0,
	0xca, 0x51, 0x5d, 0x3b, 0x9b, 0x7c, 0x27, 0x43, 0xe3, 0x85, 0x08, 0x13, 0x2a, 0x4f, 0x5a, 0x77,
	0x50, 0x53, 0xca, 0xb8, 0x05, 0x95, 0x19, 0x4b, 0x52, 0x53, 0x06, 0x5d, 0x7d, 0xe2, 0x0e, 0x1c,
	0x2c, 0xdd, 0x79, 0xcc, 0x4c, 0x6d, 0x80, 0xec, 0x0a, 0xcd, 0xc0, 0xbd, 0x76, 0x8b, 0x48, 0x1b,
	0x8e, 0x95, 0x11, 0xd2, 0xe8, 0x25, 0x34, 0xca, 0x26, 0x4d, 0xa8, 0x06, 0xf1, 0x74, 0xc6, 0x92,
	0xcc, 0xa5, 0x41, 0x73, 0x48, 0x7e, 0x90, 0x9c, 0x4d, 0x59, 0xc0, 0x43, 0x81, 0xfb, 0x60, 0x7c,
	0xb2, 0x38, 0xf4, 0x23, 0xe1, 0x7b, 0xd2, 0xc1, 0xba, 0x80, 0x1f, 0x8a, 0xb0, 0x5a, 0x1a, 0xf6,
	0x62, 0x23, 0xec, 0x5a, 0xe8, 0x1f, 0x72, 0x22, 0x35, 0xe7, 0x18, 0x9a, 0xe5, 0x90, 0x78, 0x04,
	0xd5, 0x30, 0x1d, 0x95, 0xdf, 0xfc, 0xc9, 0x4e, 0x33, 0x34, 0x67, 0x0e, 0x7f, 0x35, 0x30, 0x1e,
	0x73, 0x16, 0x7e, 0x06, 0x3d, 0x7b, 0x62, 0xdc, 0xdb, 0x38, 0xab, 0xee, 0x89, 0xd5, 0xdf, 0xde,
	0x94, 0x3e, 0xde, 0xa0, 0xae, 0x6e, 0x0b, 0x3e, 0x2f, 0xb3, 0xb7, 0x2c, 0x9e, 0x45, 0xf6, 0x51,
	0xa4, 0xec, 0x0b, 0x18, 0xc5, 0xc3, 0xe2, 0xd3, 0xfd, 0x4b, 0x65, 0x9d, 0xed, 0xec, 0x4b, 0xb5,
	0x55, 0xd2, 0x4c, 0xaa, 0xb7, 0xe5, 0x96, 0x76, 0x26, 0x2d, 0x89, 0x4c, 0xf5, 0xf4, 0xb7, 0x1c,
	0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x2b, 0x55, 0x5e, 0xb6, 0x03, 0x00, 0x00,
}
