// Code generated by protoc-gen-go. DO NOT EDIT.
// source: autopilotrpc/autopilot.proto

/*
Package autopilotrpc is a generated protocol buffer package.

It is generated from these files:
	autopilotrpc/autopilot.proto

It has these top-level messages:
	GetStatusRequest
	GetStatusResponse
	EnableRequest
	EnableResponse
*/
package autopilotrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetStatusRequest struct {
}

func (m *GetStatusRequest) Reset()                    { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()               {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetStatusResponse struct {
	// / Indicates whther the autopilot is active or not.
	Active bool `protobuf:"varint,1,opt,name=active" json:"active,omitempty"`
}

func (m *GetStatusResponse) Reset()                    { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()               {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetStatusResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type EnableRequest struct {
	// / Whether the autopilot agent should be enabled or not.
	Enable bool `protobuf:"varint,1,opt,name=enable" json:"enable,omitempty"`
}

func (m *EnableRequest) Reset()                    { *m = EnableRequest{} }
func (m *EnableRequest) String() string            { return proto.CompactTextString(m) }
func (*EnableRequest) ProtoMessage()               {}
func (*EnableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EnableRequest) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

type EnableResponse struct {
}

func (m *EnableResponse) Reset()                    { *m = EnableResponse{} }
func (m *EnableResponse) String() string            { return proto.CompactTextString(m) }
func (*EnableResponse) ProtoMessage()               {}
func (*EnableResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*GetStatusRequest)(nil), "autopilotrpc.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "autopilotrpc.GetStatusResponse")
	proto.RegisterType((*EnableRequest)(nil), "autopilotrpc.EnableRequest")
	proto.RegisterType((*EnableResponse)(nil), "autopilotrpc.EnableResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Autopilot service

type AutopilotClient interface {
	// *
	// GetStatus returns the status of the daemon's autopilot agent.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// *
	// Enable is used to enable or disable the autopilot agent.
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error)
}

type autopilotClient struct {
	cc *grpc.ClientConn
}

func NewAutopilotClient(cc *grpc.ClientConn) AutopilotClient {
	return &autopilotClient{cc}
}

func (c *autopilotClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := grpc.Invoke(ctx, "/autopilotrpc.Autopilot/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autopilotClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*EnableResponse, error) {
	out := new(EnableResponse)
	err := grpc.Invoke(ctx, "/autopilotrpc.Autopilot/Enable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Autopilot service

type AutopilotServer interface {
	// *
	// GetStatus returns the status of the daemon's autopilot agent.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// *
	// Enable is used to enable or disable the autopilot agent.
	Enable(context.Context, *EnableRequest) (*EnableResponse, error)
}

func RegisterAutopilotServer(s *grpc.Server, srv AutopilotServer) {
	s.RegisterService(&_Autopilot_serviceDesc, srv)
}

func _Autopilot_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutopilotServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autopilotrpc.Autopilot/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutopilotServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Autopilot_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutopilotServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autopilotrpc.Autopilot/Enable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutopilotServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Autopilot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "autopilotrpc.Autopilot",
	HandlerType: (*AutopilotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Autopilot_GetStatus_Handler,
		},
		{
			MethodName: "Enable",
			Handler:    _Autopilot_Enable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "autopilotrpc/autopilot.proto",
}

func init() { proto.RegisterFile("autopilotrpc/autopilot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2c, 0x2d, 0xc9,
	0x2f, 0xc8, 0xcc, 0xc9, 0x2f, 0x29, 0x2a, 0x48, 0xd6, 0x87, 0x73, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x78, 0x90, 0x65, 0x95, 0x84, 0xb8, 0x04, 0xdc, 0x53, 0x4b, 0x82, 0x4b, 0x12, 0x4b,
	0x4a, 0x8b, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0xb4, 0xb9, 0x04, 0x91, 0xc4, 0x8a,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x12, 0x93, 0x4b, 0x32, 0xcb, 0x52, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x82, 0xa0, 0x3c, 0x25, 0x75, 0x2e, 0x5e, 0xd7, 0xbc, 0xc4, 0xa4,
	0x9c, 0x54, 0xa8, 0x6e, 0x90, 0xc2, 0x54, 0xb0, 0x00, 0x4c, 0x21, 0x84, 0xa7, 0x24, 0xc0, 0xc5,
	0x07, 0x53, 0x08, 0x31, 0xd2, 0x68, 0x1e, 0x23, 0x17, 0xa7, 0x23, 0xcc, 0x31, 0x42, 0x3e, 0x5c,
	0x9c, 0x70, 0x5b, 0x85, 0xe4, 0xf4, 0x90, 0x5d, 0xa9, 0x87, 0xee, 0x44, 0x29, 0x79, 0x9c, 0xf2,
	0x50, 0xe7, 0x3a, 0x73, 0xb1, 0x41, 0x6c, 0x13, 0x92, 0x46, 0x55, 0x8a, 0xe2, 0x58, 0x29, 0x19,
	0xec, 0x92, 0x10, 0x43, 0x92, 0xd8, 0xc0, 0x21, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xac,
	0xa5, 0x10, 0xad, 0x51, 0x01, 0x00, 0x00,
}
