// Code generated by go generate; DO NOT EDIT.
package main

import "github.com/lightningnetwork/lnd/input"

var SizeConstants = []constPair{
	{
		name: "AcceptedHtlcPenaltyWitnessSize",
		size: input.AcceptedHtlcPenaltyWitnessSize,
		doc:  "AcceptedHtlcPenaltyWitnessSize 250",
	},
	{
		name: "AcceptedHtlcPenaltyWitnessSizeConfirmed",
		size: input.AcceptedHtlcPenaltyWitnessSizeConfirmed,
		doc:  "AcceptedHtlcPenaltyWitnessSizeConfirmed 253",
	},
	{
		name: "AcceptedHtlcScriptSize",
		size: input.AcceptedHtlcScriptSize,
		doc:  "AcceptedHtlcScriptSize 140",
	},
	{
		name: "AcceptedHtlcScriptSizeConfirmed",
		size: input.AcceptedHtlcScriptSizeConfirmed,
		doc:  "AcceptedHtlcScriptSizeConfirmed 143",
	},
	{
		name: "AcceptedHtlcSuccessWitnessSize",
		size: input.AcceptedHtlcSuccessWitnessSize,
		doc:  "AcceptedHtlcSuccessWitnessSize 324",
	},
	{
		name: "AcceptedHtlcSuccessWitnessSizeConfirmed",
		size: input.AcceptedHtlcSuccessWitnessSizeConfirmed,
		doc:  "AcceptedHtlcSuccessWitnessSizeConfirmed 327",
	},
	{
		name: "AcceptedHtlcTimeoutWitnessSize",
		size: input.AcceptedHtlcTimeoutWitnessSize,
		doc:  "AcceptedHtlcTimeoutWitnessSize 217",
	},
	{
		name: "AcceptedHtlcTimeoutWitnessSizeConfirmed",
		size: input.AcceptedHtlcTimeoutWitnessSizeConfirmed,
		doc:  "AcceptedHtlcTimeoutWitnessSizeConfirmed 220",
	},
	{
		name: "AnchorCommitWeight",
		size: input.AnchorCommitWeight,
		doc:  "AnchorCommitWeight 1124",
	},
	{
		name: "AnchorScriptSize",
		size: input.AnchorScriptSize,
		doc:  "AnchorScriptSize 40",
	},
	{
		name: "AnchorWitnessSize",
		size: input.AnchorWitnessSize,
		doc:  "AnchorWitnessSize 116",
	},
	{
		name: "BaseAnchorCommitmentTxSize",
		size: input.BaseAnchorCommitmentTxSize,
		doc:  "BaseAnchorCommitmentTxSize 225",
	},
	{
		name: "BaseAnchorCommitmentTxWeight",
		size: input.BaseAnchorCommitmentTxWeight,
		doc:  "BaseAnchorCommitmentTxWeight 900",
	},
	{
		name: "BaseCommitmentTxSize",
		size: input.BaseCommitmentTxSize,
		doc:  "BaseCommitmentTxSize 125",
	},
	{
		name: "BaseCommitmentTxWeight",
		size: input.BaseCommitmentTxWeight,
		doc:  "BaseCommitmentTxWeight 500",
	},
	{
		name: "BaseTxSize",
		size: input.BaseTxSize,
		doc:  "BaseTxSize 8",
	},
	{
		name: "CommitWeight",
		size: input.CommitWeight,
		doc:  "CommitWeight 724",
	},
	{
		name: "CommitmentAnchorOutput",
		size: input.CommitmentAnchorOutput,
		doc:  "CommitmentAnchorOutput 43",
	},
	{
		name: "CommitmentDelayOutput",
		size: input.CommitmentDelayOutput,
		doc:  "CommitmentDelayOutput 43",
	},
	{
		name: "CommitmentKeyHashOutput",
		size: input.CommitmentKeyHashOutput,
		doc:  "CommitmentKeyHashOutput 31",
	},
	{
		name: "FundingInputSize",
		size: input.FundingInputSize,
		doc:  "FundingInputSize 41",
	},
	{
		name: "HTLCSize",
		size: input.HTLCSize,
		doc:  "HTLCSize 43",
	},
	{
		name: "HTLCWeight",
		size: input.HTLCWeight,
		doc:  "HTLCWeight 172",
	},
	{
		name: "HtlcConfirmedScriptOverhead",
		size: input.HtlcConfirmedScriptOverhead,
		doc:  "HtlcConfirmedScriptOverhead 3",
	},
	{
		name: "HtlcSuccessWeight",
		size: input.HtlcSuccessWeight,
		doc:  "HtlcSuccessWeight 703",
	},
	{
		name: "HtlcSuccessWeightConfirmed",
		size: input.HtlcSuccessWeightConfirmed,
		doc:  "HtlcSuccessWeightConfirmed 706",
	},
	{
		name: "HtlcTimeoutWeight",
		size: input.HtlcTimeoutWeight,
		doc:  "HtlcTimeoutWeight 663",
	},
	{
		name: "HtlcTimeoutWeightConfirmed",
		size: input.HtlcTimeoutWeightConfirmed,
		doc:  "HtlcTimeoutWeightConfirmed 666",
	},
	{
		name: "InputSize",
		size: input.InputSize,
		doc:  "InputSize 41",
	},
	{
		name: "MaxHTLCNumber",
		size: input.MaxHTLCNumber,
		doc:  "MaxHTLCNumber 966",
	},
	{
		name: "MultiSigSize",
		size: input.MultiSigSize,
		doc:  "MultiSigSize 71",
	},
	{
		name: "MultiSigWitnessSize",
		size: input.MultiSigWitnessSize,
		doc:  "MultiSigWitnessSize 222",
	},
	{
		name: "NestedP2WPKHSize",
		size: input.NestedP2WPKHSize,
		doc:  "NestedP2WPKHSize 23",
	},
	{
		name: "NestedP2WSHSize",
		size: input.NestedP2WSHSize,
		doc:  "NestedP2WSHSize 35",
	},
	{
		name: "OfferedHtlcPenaltyWitnessSize",
		size: input.OfferedHtlcPenaltyWitnessSize,
		doc:  "OfferedHtlcPenaltyWitnessSize 243",
	},
	{
		name: "OfferedHtlcPenaltyWitnessSizeConfirmed",
		size: input.OfferedHtlcPenaltyWitnessSizeConfirmed,
		doc:  "OfferedHtlcPenaltyWitnessSizeConfirmed 246",
	},
	{
		name: "OfferedHtlcScriptSize",
		size: input.OfferedHtlcScriptSize,
		doc:  "OfferedHtlcScriptSize 133",
	},
	{
		name: "OfferedHtlcScriptSizeConfirmed",
		size: input.OfferedHtlcScriptSizeConfirmed,
		doc:  "OfferedHtlcScriptSizeConfirmed 136",
	},
	{
		name: "OfferedHtlcSuccessWitnessSize",
		size: input.OfferedHtlcSuccessWitnessSize,
		doc:  "OfferedHtlcSuccessWitnessSize 242",
	},
	{
		name: "OfferedHtlcSuccessWitnessSizeConfirmed",
		size: input.OfferedHtlcSuccessWitnessSizeConfirmed,
		doc:  "OfferedHtlcSuccessWitnessSizeConfirmed 245",
	},
	{
		name: "OfferedHtlcTimeoutWitnessSize",
		size: input.OfferedHtlcTimeoutWitnessSize,
		doc:  "OfferedHtlcTimeoutWitnessSize 285",
	},
	{
		name: "OfferedHtlcTimeoutWitnessSizeConfirmed",
		size: input.OfferedHtlcTimeoutWitnessSizeConfirmed,
		doc:  "OfferedHtlcTimeoutWitnessSizeConfirmed 288",
	},
	{
		name: "P2PKHOutputSize",
		size: input.P2PKHOutputSize,
		doc:  "P2PKHOutputSize 34",
	},
	{
		name: "P2PKHScriptSigSize",
		size: input.P2PKHScriptSigSize,
		doc:  "P2PKHScriptSigSize 108",
	},
	{
		name: "P2SHOutputSize",
		size: input.P2SHOutputSize,
		doc:  "P2SHOutputSize 32",
	},
	{
		name: "P2WKHOutputSize",
		size: input.P2WKHOutputSize,
		doc:  "P2WKHOutputSize 31",
	},
	{
		name: "P2WKHWitnessSize",
		size: input.P2WKHWitnessSize,
		doc:  "P2WKHWitnessSize 109",
	},
	{
		name: "P2WPKHSize",
		size: input.P2WPKHSize,
		doc:  "P2WPKHSize 22",
	},
	{
		name: "P2WSHOutputSize",
		size: input.P2WSHOutputSize,
		doc:  "P2WSHOutputSize 43",
	},
	{
		name: "P2WSHSize",
		size: input.P2WSHSize,
		doc:  "P2WSHSize 34",
	},
	{
		name: "ToLocalPenaltyWitnessSize",
		size: input.ToLocalPenaltyWitnessSize,
		doc:  "ToLocalPenaltyWitnessSize 157",
	},
	{
		name: "ToLocalScriptSize",
		size: input.ToLocalScriptSize,
		doc:  "ToLocalScriptSize 79",
	},
	{
		name: "ToLocalTimeoutWitnessSize",
		size: input.ToLocalTimeoutWitnessSize,
		doc:  "ToLocalTimeoutWitnessSize 156",
	},
	{
		name: "ToRemoteConfirmedScriptSize",
		size: input.ToRemoteConfirmedScriptSize,
		doc:  "ToRemoteConfirmedScriptSize 37",
	},
	{
		name: "ToRemoteConfirmedWitnessSize",
		size: input.ToRemoteConfirmedWitnessSize,
		doc:  "ToRemoteConfirmedWitnessSize 113",
	},
	{
		name: "WitnessCommitmentTxWeight",
		size: input.WitnessCommitmentTxWeight,
		doc:  "WitnessCommitmentTxWeight 224",
	},
	{
		name: "WitnessHeaderSize",
		size: input.WitnessHeaderSize,
		doc:  "WitnessHeaderSize 2",
	},
}
